import { Tool } from '@/types';

export const tools: Tool[] = [
  {
    id: '1',
    name: 'Qual é meu IP',
    description: 'Descubra seu endereço IP público instantaneamente',
    icon: '🌐',
    slug: 'meu-ip',
    category: 'Rede',
    keywords: ['ip', 'endereço ip', 'meu ip', 'ip público', 'localização'],
    metaDescription: 'Descubra qual é seu endereço IP público de forma rápida e gratuita. Ferramenta online para verificar seu IP.',
  },
  {
    id: '2',
    name: 'Gerador de QR Code',
    description: 'Crie QR codes personalizados gratuitamente',
    icon: '📱',
    slug: 'gerador-qr-code',
    category: 'Gerador',
    keywords: ['qr code', 'gerador qr', 'criar qr code', 'qr code grátis'],
    metaDescription: 'Gere QR codes gratuitamente online. Crie códigos QR personalizados para URLs, textos e mais.',
  },
  {
    id: '3',
    name: 'Contador de Texto',
    description: 'Conte caracteres, palavras, sentenças e parágrafos em tempo real',
    icon: '📝',
    slug: 'contador-texto',
    category: 'Texto',
    keywords: ['contador palavras', 'contador caracteres', 'contar palavras', 'contar caracteres', 'texto', 'estatísticas texto'],
    metaDescription: 'Contador de texto completo online gratuito. Conte caracteres, palavras, sentenças, parágrafos e tempo de leitura em tempo real.',
  },
  {
    id: '4',
    name: 'Converter PDF para JPG',
    description: 'Converta páginas de PDF em imagens JPG',
    icon: '📄',
    slug: 'converter-pdf-jpg',
    category: 'Conversor',
    keywords: ['pdf para jpg', 'converter pdf', 'pdf to jpg', 'imagem pdf'],
    metaDescription: 'Converta PDF para JPG online grátis. Transforme páginas de PDF em imagens de alta qualidade.',
  },
  {
    id: '5',
    name: 'Converter JPG para PDF',
    description: 'Transforme imagens JPG em documentos PDF',
    icon: '🖼️',
    slug: 'converter-jpg-pdf',
    category: 'Conversor',
    keywords: ['jpg para pdf', 'converter imagem', 'jpg to pdf', 'imagem pdf'],
    metaDescription: 'Converta JPG para PDF online grátis. Transforme suas imagens em documentos PDF facilmente.',
  },
  {
    id: '6',
    name: 'Comprimir Imagem',
    description: 'Reduza o tamanho das suas imagens sem perder qualidade',
    icon: '🗜️',
    slug: 'comprimir-imagem',
    category: 'Imagem',
    keywords: ['comprimir imagem', 'reduzir tamanho', 'otimizar imagem', 'compressão'],
    metaDescription: 'Comprima imagens online grátis. Reduza o tamanho de JPG, PNG e WebP mantendo a qualidade.',
  },
  {
    id: '7',
    name: 'Redimensionar Imagem',
    description: 'Altere as dimensões das suas imagens facilmente',
    icon: '📐',
    slug: 'redimensionar-imagem',
    category: 'Imagem',
    keywords: ['redimensionar imagem', 'resize', 'tamanho imagem', 'dimensões'],
    metaDescription: 'Redimensione imagens online grátis. Altere largura e altura de imagens mantendo proporções.',
  },
  {
    id: '8',
    name: 'Calculadora de Porcentagem',
    description: 'Calcule porcentagens de forma rápida e fácil',
    icon: '🔢',
    slug: 'calculadora-porcentagem',
    category: 'Calculadora',
    keywords: ['porcentagem', 'calcular porcentagem', 'percentual', 'calculadora'],
    metaDescription: 'Calculadora de porcentagem online grátis. Calcule percentuais, descontos e aumentos facilmente.',
  },
  {
    id: '9',
    name: 'Gerador de Senha Segura',
    description: 'Gere senhas fortes e seguras aleatoriamente',
    icon: '🔐',
    slug: 'gerador-senha',
    category: 'Segurança',
    keywords: ['senha', 'gerador senha', 'senha segura', 'password', 'senha forte'],
    metaDescription: 'Gerador de senhas seguras online. Crie senhas fortes com letras, números e símbolos gratuitamente.',
  },
  {
    id: '10',
    name: 'Converter PNG para JPG',
    description: 'Converta imagens PNG para formato JPG',
    icon: '🔄',
    slug: 'converter-png-jpg',
    category: 'Conversor',
    keywords: ['png para jpg', 'converter png', 'png to jpg', 'formato imagem'],
    metaDescription: 'Converta PNG para JPG online grátis. Transforme imagens PNG em JPG rapidamente.',
  },
  {
    id: '11',
    name: 'Gerador Lorem Ipsum',
    description: 'Gere texto placeholder para seus projetos',
    icon: '📋',
    slug: 'gerador-lorem-ipsum',
    category: 'Gerador',
    keywords: ['lorem ipsum', 'texto falso', 'placeholder', 'dummy text'],
    metaDescription: 'Gerador de Lorem Ipsum online grátis. Crie textos placeholder para seus projetos e designs.',
  },
  {
    id: '13',
    name: 'Testar se Site está Online',
    description: 'Verifique se um website está acessível',
    icon: '🌍',
    slug: 'site-online',
    category: 'Rede',
    keywords: ['site online', 'testar site', 'website down', 'disponibilidade'],
    metaDescription: 'Teste se um site está online. Verifique a disponibilidade de websites gratuitamente.',
  },
  {
    id: '14',
    name: 'Meu User Agent',
    description: 'Descubra informações sobre seu navegador',
    icon: '🖥️',
    slug: 'meu-user-agent',
    category: 'Rede',
    keywords: ['user agent', 'navegador', 'browser', 'sistema operacional'],
    metaDescription: 'Descubra seu User Agent. Veja informações sobre seu navegador e sistema operacional.',
  },
  {
    id: '15',
    name: 'Converter WebP para JPG',
    description: 'Converta imagens WebP para formato JPG',
    icon: '🎨',
    slug: 'converter-webp-jpg',
    category: 'Conversor',
    keywords: ['webp para jpg', 'converter webp', 'webp to jpg', 'formato imagem'],
    metaDescription: 'Converta WebP para JPG online grátis. Transforme imagens WebP em JPG facilmente.',
  },
  {
    id: '16',
    name: 'Regra de Três Online',
    description: 'Resolva cálculos de regra de três simples',
    icon: '➗',
    slug: 'regra-de-tres',
    category: 'Calculadora',
    keywords: ['regra de três', 'proporção', 'cálculo', 'matemática'],
    metaDescription: 'Calculadora de regra de três online grátis. Resolva proporções e cálculos facilmente.',
  },
  {
    id: '17',
    name: 'Gerador de Hash',
    description: 'Gere hashes MD5, SHA-1, SHA-256 de textos',
    icon: '🔒',
    slug: 'gerador-hash',
    category: 'Segurança',
    keywords: ['hash', 'md5', 'sha', 'criptografia', 'checksum'],
    metaDescription: 'Gerador de Hash online grátis. Crie hashes MD5, SHA-1 e SHA-256 de textos.',
  },
  {
    id: '18',
    name: 'JSON Formatter',
    description: 'Formate e valide código JSON',
    icon: '{ }',
    slug: 'json-formatter',
    category: 'Desenvolvedor',
    keywords: ['json', 'formatter', 'validar json', 'formatar json', 'pretty print'],
    metaDescription: 'Formatador JSON online grátis. Formate, valide e embeleze código JSON facilmente.',
  },
  {
    id: '19',
    name: 'Conversor MB/KB/GB',
    description: 'Converta unidades de armazenamento digital',
    icon: '💾',
    slug: 'conversor-bytes',
    category: 'Conversor',
    keywords: ['mb', 'kb', 'gb', 'bytes', 'converter bytes', 'armazenamento'],
    metaDescription: 'Conversor de bytes online grátis. Converta MB, KB, GB e outras unidades de armazenamento.',
  },
  {
    id: '20',
    name: 'Gerador de UUID',
    description: 'Gere identificadores únicos universais (UUID v4)',
    icon: '🆔',
    slug: 'gerador-uuid',
    category: 'Gerador',
    keywords: ['uuid', 'guid', 'identificador único', 'gerador uuid'],
    metaDescription: 'Gerador de UUID online grátis. Crie identificadores únicos universais (UUID v4) instantaneamente.',
  },
  {
    id: '21',
    name: 'Gerador de Link WhatsApp',
    description: 'Crie links diretos para WhatsApp com mensagem pré-definida',
    icon: '💬',
    slug: 'gerador-link-whatsapp',
    category: 'Marketing',
    keywords: ['whatsapp', 'link whatsapp', 'wa.me', 'whatsapp business', 'qr code whatsapp'],
    metaDescription: 'Gerador de link WhatsApp online grátis. Crie links diretos com mensagem pré-definida e QR Code para WhatsApp.',
  },
  {
    id: '22',
    name: 'Gerador de Chave PIX',
    description: 'Gere QR Code PIX e código Copia e Cola',
    icon: '🇧🇷',
    slug: 'gerador-chave-pix',
    category: 'Financeiro',
    keywords: ['pix', 'qr code pix', 'chave pix', 'pagamento pix', 'copia e cola pix'],
    metaDescription: 'Gerador de QR Code PIX online grátis. Crie códigos PIX para receber pagamentos com chave, valor e QR Code.',
  },
  {
    id: '23',
    name: 'Lista de Emojis',
    description: 'Copie e cole emojis com um clique',
    icon: '😀',
    slug: 'lista-emojis',
    category: 'Texto',
    keywords: ['emoji', 'emoticon', 'copiar emoji', 'lista emoji', 'símbolos'],
    metaDescription: 'Lista completa de emojis para copiar e colar. Mais de 700 emojis organizados por categoria. Copie com um clique!',
  },
  {
    id: '24',
    name: 'Cronômetro e Timer Online',
    description: 'Cronômetro e timer com modo tela cheia',
    icon: '⏱️',
    slug: 'cronometro-timer',
    category: 'Utilitário',
    keywords: ['cronômetro', 'timer', 'temporizador', 'contagem regressiva', 'alarme'],
    metaDescription: 'Cronômetro e timer online grátis. Modo tela cheia, alarme sonoro, perfeito para treinos e estudos.',
  },
  {
    id: '25',
    name: 'Cotação de Moedas',
    description: 'Conversão de moedas em tempo real',
    icon: '💱',
    slug: 'cotacao-moedas',
    category: 'Financeiro',
    keywords: ['cotação', 'moeda', 'câmbio', 'dólar', 'euro', 'real', 'conversor moeda'],
    metaDescription: 'Cotação de moedas em tempo real. Converta entre 17 moedas com taxas atualizadas do Banco Central Europeu.',
  },
  {
    id: '26',
    name: 'Conversor JSON para CSV',
    description: 'Converta JSON para CSV e vice-versa',
    icon: '🔄',
    slug: 'conversor-json-csv',
    category: 'Desenvolvedor',
    keywords: ['json', 'csv', 'conversor', 'json para csv', 'csv para json'],
    metaDescription: 'Conversor JSON para CSV online grátis. Converta entre JSON e CSV de forma bidirecional instantaneamente.',
  },
  {
    id: '27',
    name: 'Gerador de UTMs',
    description: 'Crie URLs com parâmetros UTM para rastreamento',
    icon: '📊',
    slug: 'gerador-utm',
    category: 'Marketing',
    keywords: ['utm', 'google analytics', 'rastreamento', 'marketing', 'campanha'],
    metaDescription: 'Gerador de parâmetros UTM online grátis. Crie URLs rastreáveis para campanhas de marketing digital.',
  },
  {
    id: '28',
    name: 'Calculadora de Juros Compostos',
    description: 'Calcule rendimentos de investimentos com juros compostos',
    icon: '💰',
    slug: 'calculadora-juros',
    category: 'Financeiro',
    keywords: ['juros compostos', 'investimento', 'rentabilidade', 'poupança', 'calculadora financeira'],
    metaDescription: 'Calculadora de juros compostos online grátis. Simule rendimentos de investimentos, poupança e aplicações financeiras.',
  },
  {
    id: '29',
    name: 'Feriados Nacionais 2026',
    description: 'Calendário de feriados 2026 - Brasil e mundo',
    icon: '📅',
    slug: 'feriados-2026',
    category: 'Utilitário',
    keywords: ['feriados', 'feriados 2026', 'calendário', 'feriados brasil', 'feriados nacionais'],
    metaDescription: 'Calendário completo de feriados nacionais 2026. Brasil, EUA, Espanha, México, Argentina, Chile e Colômbia.',
  },
  {
    id: '30',
    name: 'Teleprompter Online',
    description: 'Teleprompter profissional com ajustes de velocidade e espelhamento',
    icon: '📜',
    slug: 'teleprompter',
    category: 'Criador de Conteúdo',
    keywords: ['teleprompter', 'prompter', 'roteiro', 'gravação vídeo', 'apresentação'],
    metaDescription: 'Teleprompter online grátis com controle de velocidade, tamanho de fonte, modo espelho e tela cheia. Perfeito para gravações e apresentações.',
  },
  {
    id: '31',
    name: 'Calculadora de ROI',
    description: 'Calcule o retorno sobre investimento (ROI) com facilidade',
    icon: '📈',
    slug: 'calculadora-roi',
    category: 'Financeiro',
    keywords: ['roi', 'retorno investimento', 'lucro', 'rentabilidade', 'calculadora roi'],
    metaDescription: 'Calculadora de ROI online grátis. Calcule o retorno sobre investimento, lucro e rentabilidade com URL compartilhável.',
  },
  {
    id: '32',
    name: 'Gravador de Tela e Webcam',
    description: 'Grave sua tela, webcam ou ambos com áudio',
    icon: '🎥',
    slug: 'gravador-tela',
    category: 'Criador de Conteúdo',
    keywords: ['gravador tela', 'screen recorder', 'gravar tela', 'gravação webcam', 'captura tela'],
    metaDescription: 'Gravador de tela e webcam online grátis. Grave sua tela, câmera ou ambos com áudio. Sem upload, 100% privado.',
  },
  {
    id: '33',
    name: 'Testador de Microfone e Câmera',
    description: 'Teste se seu microfone e webcam estão funcionando',
    icon: '🎤',
    slug: 'testador-microfone-camera',
    category: 'Utilitário',
    keywords: ['testar microfone', 'testar camera', 'teste webcam', 'audio video', 'dispositivos'],
    metaDescription: 'Teste microfone e câmera online grátis. Verifique se seus dispositivos de áudio e vídeo estão funcionando corretamente.',
  },
  {
    id: '34',
    name: 'Gerador de Números Aleatórios',
    description: 'Gere números aleatórios com ou sem repetição',
    icon: '🎲',
    slug: 'gerador-numero-aleatorio',
    category: 'Gerador',
    keywords: ['numero aleatorio', 'random number', 'sorteio numero', 'gerador aleatorio'],
    metaDescription: 'Gerador de números aleatórios online grátis. Gere números com intervalo personalizável, com ou sem repetição.',
  },
  {
    id: '35',
    name: 'Gerador de Números da Loteria',
    description: 'Gere números para Mega-Sena, Powerball e outras loterias',
    icon: '🍀',
    slug: 'gerador-loteria',
    category: 'Gerador',
    keywords: ['loteria', 'mega sena', 'powerball', 'numeros sorte', 'gerador loteria'],
    metaDescription: 'Gerador de números da loteria online grátis. Mega-Sena, Powerball, EuroMillions e loterias personalizadas.',
  },
  {
    id: '36',
    name: 'Amigo Oculto (Secret Santa)',
    description: 'Organize sorteios de amigo oculto de forma fácil',
    icon: '🎁',
    slug: 'amigo-oculto',
    category: 'Utilitário',
    keywords: ['amigo oculto', 'secret santa', 'sorteio', 'amigo secreto', 'natal'],
    metaDescription: 'Organize amigo oculto online grátis. Sorteio automático de Secret Santa com revelação individual e exportação.',
  },
  {
    id: '37',
    name: 'Roleta da Sorte',
    description: 'Crie uma roleta personalizada para sorteios',
    icon: '🎡',
    slug: 'roleta-sorte',
    category: 'Gerador',
    keywords: ['roleta', 'sorteio', 'wheel fortune', 'roleta sorte', 'girar roleta'],
    metaDescription: 'Roleta da sorte online grátis. Crie roletas personalizadas para sorteios com animação suave e histórico.',
  },
  {
    id: '38',
    name: 'Validador e Gerador de Regex',
    description: 'Teste e valide expressões regulares em tempo real',
    icon: '🔍',
    slug: 'validador-regex',
    category: 'Desenvolvedor',
    keywords: ['regex', 'expressão regular', 'validador regex', 'testar regex', 'regexp'],
    metaDescription: 'Validador de Regex online grátis. Teste expressões regulares com destaque de matches, explicações e padrões comuns.',
  },
  {
    id: '39',
    name: 'Gerador de Políticas e Termos',
    description: 'Gere Privacy Policy, Terms of Service e Cookie Policy',
    icon: '📋',
    slug: 'gerador-politicas',
    category: 'Utilitário',
    keywords: ['privacy policy', 'termos uso', 'politica privacidade', 'cookie policy', 'lgpd'],
    metaDescription: 'Gerador de políticas e termos online grátis. Crie Privacy Policy, Terms of Service e Cookie Policy personalizados.',
  },
  {
    id: '40',
    name: 'Gerador de Paleta de Cores',
    description: 'Crie paletas de cores profissionais com contraste WCAG',
    icon: '🎨',
    slug: 'gerador-paleta-cores',
    category: 'Design',
    keywords: ['paleta cores', 'color palette', 'cores', 'design', 'wcag', 'contraste'],
    metaDescription: 'Gerador de paleta de cores online grátis. Crie paletas profissionais com HEX, RGB, HSL, contraste WCAG e export CSS/JSON.',
  },
  {
    id: '41',
    name: 'Teste de Velocidade de Internet',
    description: 'Meça a velocidade da sua conexão: download, upload, ping e jitter',
    icon: '⚡',
    slug: 'teste-velocidade-internet',
    category: 'Rede',
    keywords: ['teste velocidade', 'speed test', 'velocidade internet', 'download', 'upload', 'ping', 'internet'],
    metaDescription: 'Teste de velocidade de internet online grátis. Meça download, upload, ping e jitter da sua conexão. Resultados instantâneos e precisos.',
  },
  {
    id: '41',
    name: 'Mesclar PDFs',
    description: 'Combine múltiplos arquivos PDF em um único documento',
    icon: '📑',
    slug: 'mesclar-pdf',
    category: 'PDF',
    keywords: ['mesclar pdf', 'combinar pdf', 'juntar pdf', 'merge pdf'],
    metaDescription: 'Mescle múltiplos PDFs em um único arquivo online e grátis. Arraste e solte para reordenar páginas.',
  },
  {
    id: '42',
    name: 'Dividir PDF',
    description: 'Extraia páginas específicas de um arquivo PDF',
    icon: '✂️',
    slug: 'dividir-pdf',
    category: 'PDF',
    keywords: ['dividir pdf', 'split pdf', 'extrair páginas pdf', 'separar pdf'],
    metaDescription: 'Divida PDF online grátis. Extraia páginas específicas ou divida por intervalos.',
  },
  {
    id: '43',
    name: 'Girar PDF',
    description: 'Rotacione páginas PDF em 90°, 180°, 270° ou 360°',
    icon: '🔄',
    slug: 'girar-pdf',
    category: 'PDF',
    keywords: ['girar pdf', 'rotacionar pdf', 'rotate pdf', 'virar pdf'],
    metaDescription: 'Gire páginas de PDF online grátis. Rotacione todas as páginas em 90, 180 ou 270 graus.',
  },
  {
    id: '44',
    name: 'Calculadora de IMC',
    description: 'Calcule seu Índice de Massa Corporal e veja sua categoria',
    icon: '⚖️',
    slug: 'calculadora-imc',
    category: 'Saúde',
    keywords: ['imc', 'bmi', 'índice massa corporal', 'peso ideal', 'obesidade'],
    metaDescription: 'Calcule seu IMC online grátis. Descubra seu índice de massa corporal e categoria de peso.',
  },
  {
    id: '45',
    name: 'Calculadora de Idade',
    description: 'Calcule idade exata em anos, meses e dias',
    icon: '🎂',
    slug: 'calculadora-idade',
    category: 'Calculadora',
    keywords: ['idade', 'calcular idade', 'anos meses dias', 'idade exata'],
    metaDescription: 'Calcule sua idade exata em anos, meses e dias. Descubra quantos dias você viveu.',
  },
  {
    id: '46',
    name: 'Conversor de Case',
    description: 'Converta texto entre MAIÚSCULAS, minúsculas, camelCase e mais',
    icon: '🔤',
    slug: 'conversor-case',
    category: 'Texto',
    keywords: ['case', 'maiúsculas', 'minúsculas', 'camelcase', 'snake_case', 'kebab-case'],
    metaDescription: 'Converta texto entre diferentes formatos: MAIÚSCULAS, minúsculas, Title Case, camelCase, snake_case e kebab-case.',
  },
  {
    id: '47',
    name: 'Conversor Base64',
    description: 'Codifique e decodifique texto em Base64',
    icon: '🔐',
    slug: 'conversor-base64',
    category: 'Conversor',
    keywords: ['base64', 'encode', 'decode', 'codificar', 'decodificar'],
    metaDescription: 'Converta texto para Base64 e vice-versa online grátis. Encode e decode Base64 instantaneamente.',
  },
  {
    id: '48',
    name: 'Removedor de Espaços',
    description: 'Remova espaços extras, linhas duplicadas e vazias',
    icon: '🧹',
    slug: 'removedor-espacos',
    category: 'Texto',
    keywords: ['remover espaços', 'limpar texto', 'linhas duplicadas', 'espaços extras'],
    metaDescription: 'Remova espaços extras, linhas duplicadas e vazias do texto online grátis. Limpe e organize seu texto.',
  },
  {
    id: '49',
    name: 'Diferença entre Datas',
    description: 'Calcule diferença entre duas datas em anos, meses e dias',
    icon: '📅',
    slug: 'diferenca-datas',
    category: 'Calculadora',
    keywords: ['diferença datas', 'calcular dias', 'tempo entre datas', 'dias entre'],
    metaDescription: 'Calcule a diferença entre duas datas online grátis. Descubra anos, meses e dias entre datas.',
  },
  {
    id: '50',
    name: 'Proteger PDF',
    description: 'Adicione proteção por senha a arquivos PDF',
    icon: '🔒',
    slug: 'proteger-pdf',
    category: 'PDF',
    keywords: ['proteger pdf', 'senha pdf', 'criptografar pdf', 'segurança pdf', 'protect pdf'],
    metaDescription: 'Proteja PDFs com senha online grátis. Adicione segurança aos seus documentos PDF.',
  },
  {
    id: '51',
    name: 'Desbloquear PDF',
    description: 'Remova proteção e restrições de arquivos PDF',
    icon: '🔓',
    slug: 'desbloquear-pdf',
    category: 'PDF',
    keywords: ['desbloquear pdf', 'remover senha pdf', 'unlock pdf', 'pdf sem senha'],
    metaDescription: 'Desbloqueie PDFs protegidos online grátis. Remova restrições de arquivos PDF.',
  },
  {
    id: '52',
    name: 'Calculadora de Calorias',
    description: 'Calcule suas necessidades calóricas diárias baseado em TMB',
    icon: '🍎',
    slug: 'calculadora-calorias',
    category: 'Saúde',
    keywords: ['calorias', 'tmb', 'taxa metabólica', 'emagrecer', 'ganhar peso', 'calorie calculator'],
    metaDescription: 'Calcule quantas calorias você precisa por dia para manter, perder ou ganhar peso. Baseado na equação de Mifflin-St Jeor.',
  },
  {
    id: '53',
    name: 'Calculadora de Água',
    description: 'Calcule quanto água você deve beber por dia',
    icon: '💧',
    slug: 'calculadora-agua',
    category: 'Saúde',
    keywords: ['água', 'hidratação', 'quantidade água', 'ingestão água', 'water intake'],
    metaDescription: 'Calcule sua ingestão diária recomendada de água baseada em peso, atividade e clima.',
  },
  {
    id: '54',
    name: 'Calculadora de Frequência Cardíaca',
    description: 'Calcule suas zonas de frequência cardíaca para treino',
    icon: '❤️',
    slug: 'calculadora-frequencia-cardiaca',
    category: 'Saúde',
    keywords: ['frequência cardíaca', 'fc máxima', 'zonas treino', 'heart rate', 'karvonen'],
    metaDescription: 'Calcule sua frequência cardíaca máxima e zonas de treino online grátis. Baseado na fórmula de Karvonen.',
  },
  {
    id: '55',
    name: 'Conversor de Fuso Horário',
    description: 'Converta horários entre diferentes fusos horários',
    icon: '🌍',
    slug: 'conversor-fuso-horario',
    category: 'Conversor',
    keywords: ['fuso horário', 'timezone', 'converter hora', 'horário mundial', 'timezone converter'],
    metaDescription: 'Converta horários entre fusos horários online grátis. Suporta todos os principais timezones do mundo.',
  },
  {
    id: '56',
    name: 'Comparador de Texto',
    description: 'Compare dois textos e identifique diferenças',
    icon: '🔍',
    slug: 'comparador-texto',
    category: 'Texto',
    keywords: ['comparar texto', 'diferença texto', 'text compare', 'diff', 'comparação'],
    metaDescription: 'Compare dois textos online grátis. Identifique diferenças por caracteres, palavras ou linhas.',
  },
  {
    id: '57',
    name: 'Conversor de Unidades',
    description: 'Converta entre diferentes unidades de medida',
    icon: '📐',
    slug: 'conversor-unidades',
    category: 'Conversor',
    keywords: ['conversor unidades', 'converter medidas', 'comprimento', 'peso', 'temperatura', 'volume', 'unit converter'],
    metaDescription: 'Converta unidades de comprimento, peso, temperatura e volume online grátis. Suporta todas as principais unidades de medida.',
  },
  {
    id: '58',
    name: 'Calendário Perpétuo',
    description: 'Visualize o calendário de qualquer mês e ano',
    icon: '📅',
    slug: 'calendario-perpetuo',
    category: 'Data',
    keywords: ['calendário', 'calendar', 'perpetual calendar', 'datas', 'mês', 'ano'],
    metaDescription: 'Calendário perpétuo online grátis. Visualize qualquer mês de qualquer ano de 1 a 9999.',
  },
  {
    id: '59',
    name: 'Gerador de Gradientes',
    description: 'Crie gradientes CSS lindos e copie o código',
    icon: '🎨',
    slug: 'gerador-gradientes',
    category: 'Design',
    keywords: ['gradiente', 'gradient', 'css', 'cores', 'design', 'linear', 'radial'],
    metaDescription: 'Gerador de gradientes CSS online grátis. Crie gradientes lineares e radiais e copie o código CSS.',
  },
  {
    id: '60',
    name: 'Assinatura de Email',
    description: 'Crie assinaturas HTML profissionais para email',
    icon: '✉️',
    slug: 'assinatura-email',
    category: 'Produtividade',
    keywords: ['assinatura email', 'email signature', 'html email', 'assinatura profissional'],
    metaDescription: 'Gerador de assinatura de email online grátis. Crie assinaturas HTML profissionais para Gmail, Outlook e outros.',
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(tool => tool.slug === slug);
}

export function getToolMetadata(tool: Tool, baseUrl: string = 'https://ferramentasdigitais.com.br'): {
  title: string;
  description: string;
  openGraph: {
    title: string;
    description: string;
    url: string;
    siteName: string;
    locale: string;
    type: string;
  };
  twitter: {
    card: string;
    title: string;
    description: string;
  };
  keywords: string[];
} {
  return {
    title: `${tool.name} - Ferramenta Online Grátis`,
    description: tool.metaDescription,
    keywords: tool.keywords,
    openGraph: {
      title: `${tool.name} - Ferramenta Online Grátis`,
      description: tool.metaDescription,
      url: `${baseUrl}/${tool.slug}`,
      siteName: 'Ferramentas Digitais',
      locale: 'pt_BR',
      type: 'website',
    },
    twitter: {
      card: 'summary_large_image',
      title: `${tool.name} - Ferramenta Online Grátis`,
      description: tool.metaDescription,
    },
  };
}
